spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=${SPRING_DATASOURCE_PROD}
    username: SA
    password: ${SPRING_DATASOURCE_PASSWORD_PROD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_PROD}
    password: ${SPRING_MAIL_PASSWORD_PROD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  flyway:
    enabled: true
    ocations: classpath:db/migration
    baseline-on-migrate: true
  profiles:
    active: prod
